{% set name = "ta-lib" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 5629c82ea201375597e44713c169e1d62f18bb2309266865a941eeae76777a18

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ pin_compatible('numpy', lower_bound='2.0', upper_bound='3.0') }}                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - libta-lib
    - {{ pin_compatible('numpy', lower_bound='2.0', upper_bound='3.0') }}
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='2.0', upper_bound='3.0') }}

test:
  imports:
    - talib

about:
  home: https://github.com/mrjbq7/ta-lib
  summary: Python wrapper for TA-Lib
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sanurielf
    - gerrymanoim
    - llllllllll
    - richafrank
