{% set name = "ta-lib" %}
{% set version = "0.4.30" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TA-Lib-{{ version }}.tar.gz
    sha256: a8229f28e93698da30e0cbe456c62d7a88afdfc4f218dfb393b9d9a9f4169fb4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - libta-lib
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - talib

about:
  home: https://github.com/mrjbq7/ta-lib
  summary: Python wrapper for TA-Lib
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gerrymanoim
    - llllllllll
    - richafrank
