{% set name = "ta-lib" %}
{% set version = "0.4.32" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TA-Lib-{{ version }}.tar.gz
    sha256: fb74c323217bead847a045c97aa17bfd147aef17e20a75857ea0f8f7ee7cdaa0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libta-lib
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - libta-lib
    - pip
    - python
  run:
    - python

test:
  imports:
    - talib

about:
  home: https://github.com/mrjbq7/ta-lib
  summary: Python wrapper for TA-Lib
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sanurielf
    - gerrymanoim
    - llllllllll
    - richafrank
