{% set name = "ta-lib" %}
{% set version = "0.4.28" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TA-Lib-{{ version }}.tar.gz
    sha256: 3f03847162e003e0d92a8a89d9e8b7192dfe1235507e2f7d1d0e66cd5af7a48e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - libta-lib
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - talib

about:
  home: https://github.com/mrjbq7/ta-lib
  summary: Python wrapper for TA-Lib
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sanurielf
    - gerrymanoim
    - llllllllll
    - richafrank
